# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (2, 'filed'), (3, 'Need Edit'), (4, 'Need Check')], default=4),
        ),
    ]
